# Generated by Django 6.0.4 on 2026-05-09 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreprestamo', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.socio')),
            ],
        ),
        migrations.AddField(
            model_name='socio',
            name='tipo_socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.tiposocio'),
        ),
    ]
