# Generated by Django 6.0.4 on 2026-05-15 23:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('idjugador', models.AutoField(primary_key=True, serialize=False)),
                ('avatarjugador', models.CharField(blank=True, max_length=255, null=True)),
                ('aliasjugador', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('correojugador', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('fecharegistrojugador', models.DateTimeField()),
                ('saldocreditojugador', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estadocuentajugador', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Jugador',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('idmetodopago', models.AutoField(primary_key=True, serialize=False)),
                ('nombremetodopago', models.CharField(max_length=50, unique=True)),
                ('descripcionmetodopago', models.CharField(blank=True, max_length=200, null=True)),
                ('estadometodopago', models.BooleanField(default=True)),
                ('urlmetodopago', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'MetodoPago',
            },
        ),
        migrations.CreateModel(
            name='PlataformaJuego',
            fields=[
                ('idplataformajuego', models.AutoField(primary_key=True, serialize=False)),
                ('nombreplataforma', models.CharField(max_length=25, unique=True)),
                ('urlplataforma', models.CharField(max_length=255)),
                ('descripcionplataforma', models.CharField(blank=True, max_length=200, null=True)),
                ('estadoplataforma', models.BooleanField()),
                ('fechaadquisicionlicencia', models.DateField(blank=True, null=True)),
                ('fechavencimientolicencia', models.DateField(blank=True, null=True)),
                ('contactoplataforma', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'PlataformaJuego',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('idprestamo', models.AutoField(primary_key=True, serialize=False)),
                ('montoprestamosolicitado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasainteres', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('montototalpagar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldopendiente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numerocuotas', models.IntegerField(default=1)),
                ('fechasolicitud', models.DateField()),
                ('fechavencimiento', models.DateField()),
                ('estadoprestamo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Prestamo',
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('idsocio', models.AutoField(primary_key=True, serialize=False)),
                ('primernombresocio', models.CharField(max_length=40)),
                ('segundonombresocio', models.CharField(blank=True, max_length=40, null=True)),
                ('primerapellidosocio', models.CharField(max_length=40)),
                ('segundoapellidosocio', models.CharField(max_length=40)),
                ('cisocio', models.CharField(max_length=10, unique=True)),
                ('fechanacimientosocio', models.DateField()),
                ('telefonopersonalsocio', models.CharField(max_length=10)),
                ('telefonotrabajosocio', models.CharField(blank=True, max_length=25, null=True)),
                ('direcciondomiciliosocio', models.CharField(max_length=255)),
                ('direcciontrabajosocio', models.CharField(blank=True, max_length=255, null=True)),
                ('sexosocio', models.CharField(blank=True, max_length=1, null=True)),
                ('estadosocio', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Socio',
            },
        ),
        migrations.CreateModel(
            name='TipoSocio',
            fields=[
                ('idtiposocio', models.AutoField(primary_key=True, serialize=False)),
                ('nombretiposocio', models.CharField(max_length=100, unique=True)),
                ('roltiposocio', models.CharField(max_length=50, unique=True)),
                ('descripciondetiposocio', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'TipoSocio',
            },
        ),
        migrations.CreateModel(
            name='Bingo',
            fields=[
                ('idbingo', models.AutoField(primary_key=True, serialize=False)),
                ('titulobingo', models.CharField(max_length=150)),
                ('fechaprogramadabingo', models.DateTimeField()),
                ('tipobingo', models.CharField(max_length=20)),
                ('lugarbingo', models.CharField(blank=True, max_length=255, null=True)),
                ('urlsesionbingo', models.CharField(blank=True, max_length=255, null=True)),
                ('preciocarton', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premiomayor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcionpremiomayor', models.CharField(max_length=100)),
                ('estadobingo', models.CharField(max_length=20)),
                ('rutaimagenpremiomayor', models.CharField(blank=True, max_length=300, null=True)),
                ('urlvideopromocional', models.CharField(blank=True, max_length=300, null=True)),
                ('descripcionpremios', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Bingo',
                'constraints': [models.CheckConstraint(condition=models.Q(('estadobingo__in', ['Programado', 'En Curso', 'Finalizado', 'Cancelado'])), name='chk_bingo_estadobingo')],
            },
        ),
        migrations.CreateModel(
            name='PartidaBingo',
            fields=[
                ('idpartidabingo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreronda', models.CharField(max_length=100)),
                ('valorefectivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premiomaterial', models.CharField(max_length=150)),
                ('estadopartida', models.CharField(max_length=20)),
                ('bolascantadas', models.TextField()),
                ('ultimabola', models.IntegerField()),
                ('haydesempate', models.BooleanField(blank=True, null=True)),
                ('idbingadores', models.TextField(blank=True, null=True)),
                ('bolamayordesempate', models.IntegerField(blank=True, null=True)),
                ('horainicio', models.DateTimeField()),
                ('horafin', models.DateTimeField(blank=True, null=True)),
                ('idbingo', models.ForeignKey(db_column='idbingo', on_delete=django.db.models.deletion.RESTRICT, to='bingo.bingo')),
                ('idjugadorganador', models.ForeignKey(blank=True, db_column='idjugadorganador', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bingo.jugador')),
            ],
            options={
                'db_table': 'PartidaBingo',
            },
        ),
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('idcarton', models.AutoField(primary_key=True, serialize=False)),
                ('codigocarton', models.CharField(max_length=30, unique=True)),
                ('matriznumeros', models.TextField()),
                ('indicevictoria', models.IntegerField(blank=True, default=0, null=True)),
                ('preciopagado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fechacompra', models.DateTimeField(blank=True, null=True)),
                ('estadocarton', models.CharField(default='Disponible', max_length=20)),
                ('idjugador', models.ForeignKey(blank=True, db_column='idjugador', null=True, on_delete=django.db.models.deletion.RESTRICT, to='bingo.jugador')),
                ('idpartida', models.ForeignKey(blank=True, db_column='idpartida', null=True, on_delete=django.db.models.deletion.RESTRICT, to='bingo.partidabingo')),
            ],
            options={
                'db_table': 'Carton',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idpago', models.AutoField(primary_key=True, serialize=False)),
                ('montopagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numeroreferencia', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fechapago', models.DateTimeField()),
                ('fechaconfirmacionadmin', models.DateTimeField(blank=True, null=True)),
                ('comprobantepago', models.CharField(blank=True, max_length=255, null=True)),
                ('estadopago', models.CharField(blank=True, max_length=20, null=True)),
                ('idmetodopago', models.ForeignKey(db_column='idmetodopago', on_delete=django.db.models.deletion.RESTRICT, to='bingo.metodopago')),
                ('idprestamo', models.ForeignKey(db_column='idprestamo', on_delete=django.db.models.deletion.RESTRICT, to='bingo.prestamo')),
            ],
            options={
                'db_table': 'Pago',
            },
        ),
        migrations.CreateModel(
            name='Regalo',
            fields=[
                ('idregalo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreregalo', models.CharField(max_length=100)),
                ('descripcionregalo', models.CharField(blank=True, max_length=200, null=True)),
                ('valorregalo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaentregaregalo', models.DateTimeField()),
                ('estadoregalo', models.CharField(max_length=20)),
                ('fechaultimaactualizacion', models.DateTimeField()),
                ('urlimagen', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Regalo',
                'constraints': [models.CheckConstraint(condition=models.Q(('estadoregalo__in', ['Acumulado', 'Sorteado', 'Entregado'])), name='chk_regalo_estadoregalo')],
            },
        ),
        migrations.CreateModel(
            name='SesionJuego',
            fields=[
                ('idsesion', models.AutoField(primary_key=True, serialize=False)),
                ('fechainiciosesion', models.DateTimeField()),
                ('fechafinsesion', models.DateTimeField(blank=True, null=True)),
                ('ipconexion', models.CharField(blank=True, max_length=50, null=True)),
                ('dispositivoconexion', models.CharField(blank=True, max_length=50, null=True)),
                ('estadosesion', models.CharField(max_length=15)),
                ('latenciaping', models.IntegerField(blank=True, null=True)),
                ('navegadorweb', models.CharField(blank=True, max_length=150, null=True)),
                ('tokenconexion', models.CharField(max_length=255, unique=True)),
                ('motivocierre', models.CharField(blank=True, max_length=50, null=True)),
                ('idjugador', models.ForeignKey(db_column='idjugador', on_delete=django.db.models.deletion.RESTRICT, to='bingo.jugador')),
                ('idpartida', models.ForeignKey(db_column='idpartida', on_delete=django.db.models.deletion.RESTRICT, to='bingo.partidabingo')),
                ('idplataforma', models.ForeignKey(db_column='idplataforma', on_delete=django.db.models.deletion.RESTRICT, to='bingo.plataformajuego')),
            ],
            options={
                'db_table': 'SesionJuego',
            },
        ),
        migrations.AddField(
            model_name='prestamo',
            name='idsocio',
            field=models.ForeignKey(db_column='idsocio', on_delete=django.db.models.deletion.RESTRICT, to='bingo.socio'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='idsocio',
            field=models.ForeignKey(blank=True, db_column='idsocio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bingo.socio'),
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('idcuentabancaria', models.AutoField(primary_key=True, serialize=False)),
                ('nombrebanco', models.CharField(max_length=100)),
                ('numerocuenta', models.CharField(max_length=30, unique=True)),
                ('tipocuenta', models.CharField(max_length=20)),
                ('esprincipal', models.BooleanField(default=False, unique=True)),
                ('fecharegistro', models.DateTimeField(default=django.utils.timezone.now)),
                ('estadocuenta', models.CharField(max_length=10)),
                ('idsocio', models.ForeignKey(db_column='idsocio', on_delete=django.db.models.deletion.RESTRICT, to='bingo.socio')),
            ],
            options={
                'db_table': 'CuentaBancaria',
            },
        ),
        migrations.CreateModel(
            name='AporteSemanal',
            fields=[
                ('idaporte', models.AutoField(primary_key=True, serialize=False)),
                ('numerosemana', models.IntegerField(blank=True, null=True)),
                ('fechaplanificadada', models.DateTimeField()),
                ('fechaentregareal', models.DateTimeField(blank=True, null=True)),
                ('metodoingreso', models.CharField(max_length=50)),
                ('referenciaingreso', models.CharField(blank=True, max_length=100, null=True)),
                ('estadoaporte', models.CharField(blank=True, max_length=20, null=True)),
                ('idpartida', models.ForeignKey(db_column='idpartida', on_delete=django.db.models.deletion.RESTRICT, to='bingo.partidabingo')),
                ('idregalo', models.ForeignKey(db_column='idregalo', on_delete=django.db.models.deletion.RESTRICT, to='bingo.regalo')),
                ('idsocio', models.ForeignKey(db_column='idsocio', on_delete=django.db.models.deletion.RESTRICT, to='bingo.socio')),
            ],
            options={
                'db_table': 'AporteSemanal',
            },
        ),
        migrations.CreateModel(
            name='Ahorro',
            fields=[
                ('idahorro', models.AutoField(primary_key=True, serialize=False)),
                ('tipoahorro', models.CharField(max_length=50)),
                ('montoahorro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaahorro', models.DateTimeField()),
                ('comentarioahorro', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(max_length=25)),
                ('idbingo', models.ForeignKey(db_column='idbingo', on_delete=django.db.models.deletion.RESTRICT, to='bingo.bingo')),
                ('idsocio', models.ForeignKey(db_column='idsocio', on_delete=django.db.models.deletion.RESTRICT, to='bingo.socio')),
            ],
            options={
                'db_table': 'Ahorro',
            },
        ),
        migrations.AddField(
            model_name='socio',
            name='idtiposocio',
            field=models.ForeignKey(db_column='idtiposocio', on_delete=django.db.models.deletion.RESTRICT, to='bingo.tiposocio'),
        ),
        migrations.AddConstraint(
            model_name='partidabingo',
            constraint=models.CheckConstraint(condition=models.Q(('estadopartida__in', ['En Juego', 'Verificando', 'Desempate', 'Finalizada'])), name='chk_partidabingo_estadopartida'),
        ),
        migrations.AddConstraint(
            model_name='carton',
            constraint=models.CheckConstraint(condition=models.Q(('preciopagado__gte', 0)), name='chk_carton_preciopagado'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('estadopago__in', ['Pendiente', 'Validado', 'Rechazado'])), name='chk_pago_estadopago'),
        ),
        migrations.AddConstraint(
            model_name='sesionjuego',
            constraint=models.CheckConstraint(condition=models.Q(('estadosesion__in', ['Activa', 'Finalizada', 'Caida'])), name='chk_sesionjuego_estadosesion'),
        ),
        migrations.AddConstraint(
            model_name='prestamo',
            constraint=models.CheckConstraint(condition=models.Q(('estadoprestamo__in', ['Solicitado', 'Aprobado', 'En espera', 'Liquidado'])), name='chk_prestamo_estadoprestamo'),
        ),
        migrations.AddConstraint(
            model_name='prestamo',
            constraint=models.CheckConstraint(condition=models.Q(('montoprestamosolicitado__gte', 0)), name='chk_prestamo_montoprestamosolicitado'),
        ),
        migrations.AddConstraint(
            model_name='prestamo',
            constraint=models.CheckConstraint(condition=models.Q(('numerocuotas__gte', 1)), name='chk_prestamo_numerocuotas'),
        ),
        migrations.AddConstraint(
            model_name='jugador',
            constraint=models.CheckConstraint(condition=models.Q(('estadocuentajugador__in', ['Activo', 'Suspendido', 'Moroso'])), name='chk_jugador_estadocuentajugador'),
        ),
        migrations.AddConstraint(
            model_name='cuentabancaria',
            constraint=models.CheckConstraint(condition=models.Q(('tipocuenta__in', ['Ahorro', 'Corriente'])), name='chk_cuentabancaria_tipocuenta'),
        ),
        migrations.AddConstraint(
            model_name='aportesemanal',
            constraint=models.CheckConstraint(condition=models.Q(('estadoaporte__in', ['Al Dia', 'Atrasado'])), name='chk_aportesemanal_estadoaporte'),
        ),
        migrations.AddConstraint(
            model_name='aportesemanal',
            constraint=models.CheckConstraint(condition=models.Q(('metodoingreso__in', ['Efectivo', 'Transferencia', 'Fisico'])), name='chk_aportesemanal_metodoingreso'),
        ),
        migrations.AddConstraint(
            model_name='ahorro',
            constraint=models.CheckConstraint(condition=models.Q(('tipoahorro__in', ['Obligatorio', 'Voluntario'])), name='chk_ahorro_tipoahorro'),
        ),
        migrations.AddConstraint(
            model_name='ahorro',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['Activo', 'Inactivo'])), name='chk_ahorro_estado'),
        ),
        migrations.AddConstraint(
            model_name='socio',
            constraint=models.CheckConstraint(condition=models.Q(('sexosocio__in', ['H', 'M'])), name='chk_socio_sexosocio'),
        ),
        migrations.AddConstraint(
            model_name='socio',
            constraint=models.CheckConstraint(condition=models.Q(('estadosocio__in', ['Activo', 'Inactivo'])), name='chk_socio_estadosocio'),
        ),
    ]
